resources:
  - name: webhook
    type: IncomingWebhook
    configuration:
      webhookName: webhook
  - name: aql
    type: Aql
    configuration:
      sourceArtifactory: artifactory
      query: items.find({"name":"${distribution_filename}"})
  - name: release_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: StDistribution
      name: sadfhgjsadgfjkkl
      version: v2.0.0
  - name: signed_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: StDistribution
      name: sadfhgjsadgfjkkl
      version: v2.0.0
  - name: distribution_rules
    type: DistributionRule
    configuration:
      sourceDistribution: StDistribution
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "US"
pipelines:
  - name: dummy_build
    steps:
      - name: bashScript
        type: Bash
        configuration:
          inputResources:
            - name: webhook
          outputResources:
            - name: aql
        execution:
          onExecute:
            - echo "I HAVE RAN SUCCESSFULLY!"
            - set_payload webhook "$res_webhook_payload"
            - echo "$res_webhook_payload" | jq '.' > payload.json
            - set_payload webhook payload.json --file
            - cat payload.json
            - read_json payload.json "data.name"
            - add_run_variables distribution_filename=$(read_json payload.json "data.name")
            - echo $distribution_filename
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: sadfhgjsadgfjkkl
          releaseBundleVersion: v2.0.0
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: aql
              trigger: true
          outputResources:
            - name: release_bundle
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points
      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle
          outputResources:
            - name: signed_bundle
      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_bundle
            - name: distribution_rules
