resources:
  - name: webhook
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook
pipelines:
  - name: dummy_build
    steps:
      - name: bashScript
        type: Bash
        configuration:
          inputResources:
            - name: webhook
        execution:
          onExecute:
            - echo "I HAVE RAN SUCCESSFULLY!"
